name: Build Polyglot Book from Best Games in the World

on:
  workflow_dispatch:

jobs:
  build-best-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Best Games PGNs
        run: |
          mkdir -p book
          curl -L "https://www.chessdb.cn/down/pgn/worldchamp.pgn" -o book/worldchamp.pgn
          curl -L "https://www.chessdb.cn/down/pgn/supergm.pgn" -o book/supergm.pgn
          curl -L "https://www.chessdb.cn/down/pgn/linares.pgn" -o book/linares.pgn
          curl -L "https://www.chessdb.cn/down/pgn/candidates.pgn" -o book/candidates.pgn
          curl -L "https://www.chessdb.cn/down/pgn/topall.pgn" -o book/topall.pgn
          cat book/worldchamp.pgn book/supergm.pgn book/linares.pgn book/candidates.pgn book/topall.pgn > book/best_games.pgn
          ls -lh book/

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y polyglot python3 python3-pip
          pip3 install python-chess tqdm

      - name: Filter PGN for best decisive games
        run: |
          python3 - <<'EOF'
          import chess.pgn
          INPUT_PGN = "book/best_games.pgn"
          OUTPUT_PGN = "book/best_decisive_games.pgn"
          MIN_MOVES = 20          # Lowered from 30 to 20
          MIN_ELO = 2500

          def is_best_game(game):
              try:
                  white_elo = int(game.headers.get("WhiteElo", "0"))
                  black_elo = int(game.headers.get("BlackElo", "0"))
              except Exception:
                  white_elo = black_elo = 0
              result = game.headers.get("Result", "")
              if result not in ["1-0", "0-1"]:
                  return False
              if white_elo < MIN_ELO or black_elo < MIN_ELO:
                  return False
              moves = 0
              node = game
              while node.variations:
                  node = node.variation(0)
                  moves += 1
              if moves < MIN_MOVES:
                  return False
              return True

          with open(INPUT_PGN, "r", encoding="utf-8", errors="ignore") as inp, \
               open(OUTPUT_PGN, "w", encoding="utf-8") as outp:
              while True:
                  game = chess.pgn.read_game(inp)
                  if game is None:
                      break
                  if is_best_game(game):
                      outp.write(str(game) + "\n\n")
          EOF

      - name: Inspect filtered PGN file
        run: |
          echo "PGN file size:"
          ls -lh book/best_decisive_games.pgn
          echo "First 30 lines:"
          head -30 book/best_decisive_games.pgn
          echo "Number of games:"
          grep -c "\[Event" book/best_decisive_games.pgn

      - name: Generate Polyglot .bin book (up to move 50)
        run: |
          polyglot make-book \
            -pgn book/best_decisive_games.pgn \
            -bin book/world_best_book.bin \
            -min-game 1 \
            -max-ply 100
          ls -lh book/

      - name: Inspect Polyglot .bin file
        run: |
          echo ".bin file size:"
          ls -lh book/world_best_book.bin
          echo "Hex dump of first 32 bytes:"
          hexdump -C book/world_best_book.bin | head

      - name: Commit and push .bin to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f book/world_best_book.bin ] && [ -s book/world_best_book.bin ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add book/world_best_book.bin
            git commit -m "Add/Update Polyglot .bin book from world's best games (decisive, top Elo, up to move 50, multi-URL)" || echo "No changes to commit"
            git push
          else
            echo "No .bin book was created or file is empty. Skipping commit."
          fi
